extends:
  airbnb-base

env:
  node: true
  es6: true

rules:
  max-len: [error, 120]
  linebreak-style: 0
  no-console: 0
  comma-dangle: [error, always-multiline]
  quotes: [error, single]
  no-plusplus: 0
  object-curly-spacing: [error, never]
  object-curly-newline: 0
  no-param-reassign: 0
  no-await-in-loop: 0
  no-empty: [error, allowEmptyCatch: true]
  import/prefer-default-export: off
  no-nested-ternary: 0

settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - src